name: ğŸŒ¡ï¸ Scorecard supply-chain security
on:
  branch_protection_rule:
  schedule:
    - cron: "37 13 * * 3"
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    name: ğŸ•µï¸ Scorecard analysis
    runs-on: ubuntu-latest
    if: github.repository == 'remeda/remeda'
    permissions:
      security-events: write # Upload the results to code-scanning dashboard.
      id-token: write # Publish results and get a badge.

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: ğŸ” Run analysis
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: ğŸ—ƒï¸ Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: SARIF-results
          path: results.sarif
          retention-days: 7

      - name: ğŸ›¡ï¸ Upload to code-scanning
        uses: github/codeql-action/upload-sarif@b20883b0cd1f46c72ae0ba6d1090936928f9fa30 # v4.32.0
        with:
          sarif_file: results.sarif
